### ISSUE TITLE
チュートリアル

### ISSUE THREAD

**Issue by MoriKen254** [ntl-ros-pkg/motoman_moveit#3]
MoveIt! をGazeboで動作させるチュートリアルはありますか？

どのlaunchファイルをどの順番で起動すればよいか分かれば助かります。

**Comment by RyodoTanaka** [comment]
@MoriKen254 
すみません
今気づきました...

今の所，チュートリアル等のドキュメントは整理してない（全く構築していない）ので，明文化されたチュートリアルは無いです...

一応，moveit!をGazeboと起動する手順としては

- `motoman_moveit`
- `motoman_robot`
- `motoman_simulator`

をそれぞれcloneしていただいて

各パッケージ内に`.kinetic_depends.rosinstall`というファイルがあるので，それぞれwstoolでcloneしてください．
その後，`rosdep install`コマンドを使用して依存パッケージをインストールしてください．
最後に`catkin build`でビルドしてください．

ここまでで，基本的なインストールは完了です．

で，launchする方法ですが
`source devel/setup.bash`
でパス通しをした後
1. `roslaunch motoman_gazebo sia5_with_dhand.launch`
2. `roslaunch motoman_moveit_bringup sia5_with_dhand_moveit_planning_execution.launch`

以上で，KinectなしでGazebo + Moveit! のデモが立ち上がります．
なお，Gazeboを起動しなくても，Moveit!のみを立ち上げることが可能です．
やり方は，`motoman_moveit_bringup`パッケージ内の各launchファイル内にある，
`moveit_controller_manager`というargumentを`fake`に設定するとできます．
launchファイルを直接弄りたくない場合は，例として下記のように実行時に引数の値を指定してやれば起動します．
`roslaunch motoman_moveit_bringup sia5_with_dhand_moveit_planning_execution.launch moveit_controllar_manager:=fake`

以上，取り急ぎの内容でわかりづらくて申し訳ないですが，よろしくお願いします．

**Comment by MoriKen254** [comment]
ありがとうございます！

試してみます。

**Comment by MoriKen254** [comment]
こちらの質問に関連して、cirkit-unit03のときのようなappリポジトリを作成し、インストールやサンプルの利用を容易化できるようなパッケージを作成できたらなと思っているのですが、いかがでしょう。

もしよろしければ、私もこのorganizationに加えてもらえますか。

お休みの所申し訳ないのですが、私が手を動かせるのが休みの時間なので、お正月中手が空いたときに招待いただければ幸いです。宜しくおねがいします。

**Comment by RyodoTanaka** [comment]
@MoriKen254 
遅くなってすみません．
Ownerとして招待したので，よろしくお願いします．

**Comment by MoriKen254** [comment]
休み中ごめん、ありがとう！

**Comment by MoriKen254** [comment]
https://github.com/ntl-ros-pkg/motoman_apps を作成済みですので、完了ですね。

クローズ！
